import { MainLayout } from '@/components/main-layout';
import '@/styles/globals.css'
import Head from 'next/head';

export default function App({ Component, pageProps, data }) {
  return (
    <>
    <Head>
        <title> Flexmovies </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <MainLayout >
      <Component {...pageProps} data={data} />
    </MainLayout>
    </>
  )
}

App.getInitialProps = async ({ Component, ctx }) => {

  const trendDay = await fetch(
    "https://api.themoviedb.org/3/trending/all/day?api_key=8a2782e79632aea9f11727ccc210744f"
  ).then(res => res.json());
  const trendWeek = await fetch(
    "https://api.themoviedb.org/3/trending/all/week?api_key=8a2782e79632aea9f11727ccc210744f"
  ).then(res => res.json());
  const moviesNowPlaying = await fetch(
    "https://api.themoviedb.org/3/movie/now_playing?api_key=8a2782e79632aea9f11727ccc210744f&language=en-US&page=1"
  ).then(res => res.json());
  const moviesPopular = await fetch(
    "https://api.themoviedb.org/3/movie/popular?api_key=8a2782e79632aea9f11727ccc210744f&language=en-US&page=1"
  ).then(res => res.json());
  const moviesTopRated = await fetch(
    "https://api.themoviedb.org/3/movie/top_rated?api_key=8a2782e79632aea9f11727ccc210744f&language=en-US&page=1"
  ).then(res => res.json());
  const moviesUpcoming = await fetch(
    "https://api.themoviedb.org/3/movie/upcoming?api_key=8a2782e79632aea9f11727ccc210744f&language=en-US&page=1"
  ).then(res => res.json());
  const tvPopular = await fetch(
    "https://api.themoviedb.org/3/tv/popular?api_key=8a2782e79632aea9f11727ccc210744f&language=en-US&page=1"
  ).then(res => res.json());
  const tvTopRated = await fetch(
    "https://api.themoviedb.org/3/tv/top_rated?api_key=8a2782e79632aea9f11727ccc210744f&language=en-US&page=1"
  ).then(res => res.json());
  const tvOnTheAir = await fetch(
    "https://api.themoviedb.org/3/tv/on_the_air?api_key=8a2782e79632aea9f11727ccc210744f&language=en-US&page=1"
  ).then(res => res.json());
  const tvAiringToday = await fetch(
    "https://api.themoviedb.org/3/tv/airing_today?api_key=8a2782e79632aea9f11727ccc210744f&language=en-US&page=1"
  ).then(res => res.json());

  //movies
  moviesNowPlaying.results.forEach((dat) => dat.media = 'movie')
  moviesPopular.results.forEach((dat) => dat.media = 'movie')
  moviesTopRated.results.forEach((dat) => dat.media = 'movie')
  moviesUpcoming.results.forEach((dat) => dat.media = 'movie')
  //tv shows
  tvPopular.results.forEach((dat) => dat.media = 'tv');
  tvTopRated.results.forEach((dat) => dat.media = 'tv');
  tvOnTheAir.results.forEach((dat) => dat.media = 'tv');
  tvAiringToday.results.forEach((dat) => dat.media = 'tv');

  const data = {
    trendDay,
    trendWeek,
    moviesNowPlaying,
    moviesPopular,
    moviesTopRated,
    moviesUpcoming,
    tvPopular,
    tvTopRated,
    tvOnTheAir,
    tvAiringToday,
  }

  let pageProps = {};
  if (Component.getInitialProps) {
    pageProps = await Component.getInitialProps(ctx);
  }
  return { pageProps, data};
};
