"use client";
import { useState } from "react";
import Head from "next/head";
import { emailRegex } from "@/lib/emailregex";
import styles from "@/styles/Login.module.scss";
import Link from "next/link";
import ResetEmail from "@/lib/emailReset";
import { toast } from "react-toastify";

export default function EmailResetPage({data}) {
  const [email, setEmail] = useState("");
  const [error, setError] = useState({ email: "", password: "" });

  const alertError = (type) => {
    if (type === "email") {
      setError({ ...error, email: "Please type in a valid email" });
    } else {
      setError({ ...error, password: "Email or password incorrect" });
    }
  };

  const handleResetEmail = async (e) => {
    e.preventDefault();

    //check if email is in the correct format
    if (!emailRegex.test(email)) {
      alertError("email");
      return;
    }

    const error = await ResetEmail(email); //

    if (error) {
      //use toastify to alert user email reset attempt has failed
      toast.error("Error . Please try again.", {
        position: toast.POSITION.TOP_CENTER,
      });
      // then return
      return;
    }

    //alert that reset email has been sent to user's mail
    toast.success(`Reset Email has been sent to ${email}`, {
        position: toast.POSITION.TOP_CENTER,
      });
  };

  const backgroundImageUrl = `https://image.tmdb.org/t/p/original/${data.trendDay.results[0].poster_path}`

  return (
    <>
      <Head>
        <title> Reset Password || Flexmovies </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section style={{background: `url(${backgroundImageUrl})`}} className={styles.background}></section>
      <section className={styles.login}>
        <article>
          <h1>Flexmovies</h1>
          <form noValidate onSubmit={handleResetEmail}>
          <h3>Forgot Password</h3>
            <div>
            <p>Input your email and click to send an email reset link to your mail.</p>
            <label htmlFor="email">Email</label>
            <input
              id="email"
              name="email"
              className={styles.login_input}
              type="text"
              placeholder="Your email"
              value={email}
              onChange={(e) => {
                setEmail(e.target.value);
                setError("");
              }}
            />
            <span>{error.email}</span>
            </div>
            <div>
            </div>
            <article className={styles.loginbtn}>
            <button id="login-btn" type="submit" >
              Send
            </button>
            <p>
                Already have an account?{" "}
                <Link href="/login" className={styles.link}>
                  Click here to Sign In
                </Link>
              </p>
            <p>
              Do not have an account?{" "}
              <Link href="/signup" className={styles.link}>Click here to Sign Up</Link>
            </p>
            </article>
          </form>
        </article>
      </section>
    </>
  );
}
