import { HomePage } from "@/components/home-page";
import {
  fetchTrendingDay,
  fetchTrendingWeek,
  mNowPlaying,
  mTopRated,
  tAiringToday,
  tTopRated,
} from "@/utils/fetch";
import Head from "next/head";

const Home = ({ data }) => {
  console.log(data);
  return (
    <>
      <Head>
        <title> Flexmovies </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/* <HomePage data={data} /> */}
    </>
  );
  }
export default Home

export async function getServerSideProps(context) {
  const [
    trendDay,
    trendWeek,
    moviesNowPlaying,
    moviesTopRated,
    tvTopRated,
    tvAiringToday,
  ] = await Promise.all([
    fetchTrendingDay("1", process.env.NEXT_PUBLIC_TMDB_API_KEY),
    fetchTrendingWeek("1", process.env.NEXT_PUBLIC_TMDB_API_KEY),
    mNowPlaying(process.env.NEXT_PUBLIC_TMDB_API_KEY),
    mTopRated(process.env.NEXT_PUBLIC_TMDB_API_KEY),
    tTopRated(process.env.NEXT_PUBLIC_TMDB_API_KEY),
    tAiringToday(process.env.NEXT_PUBLIC_TMDB_API_KEY),
  ]);


  const data = {
    trendDay,
    trendWeek,
    moviesNowPlaying,
    moviesTopRated,
    tvTopRated,
    tvAiringToday,
  };

  return {
    props: {
      data,
    },
  };
}

