import { HomePage } from "@/components/home-page";
import {
  fetchTrendingDay,
  fetchTrendingWeek,
  mNowPlaying,
  mTopRated,
  tAiringToday,
  tTopRated,
} from "@/utils/fetch";
import Head from "next/head";
import { getPlaiceholder } from "plaiceholder";

const Home = ({ data }) => {
  console.log(data);
  return (
    <>
      <Head>
        <title> Flexmovies </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/* <HomePage data={data} /> */}
    </>
  );
  }
export default Home

export async function getServerSideProps(context) {
  const [
    trendDay,
    trendWeek,
    moviesNowPlaying,
    moviesTopRated,
    tvTopRated,
    tvAiringToday,
  ] = await Promise.all([
    fetchTrendingDay("1", process.env.NEXT_PUBLIC_TMDB_API_KEY),
    fetchTrendingWeek("1", process.env.NEXT_PUBLIC_TMDB_API_KEY),
    mNowPlaying(process.env.NEXT_PUBLIC_TMDB_API_KEY),
    mTopRated(process.env.NEXT_PUBLIC_TMDB_API_KEY),
    tTopRated(process.env.NEXT_PUBLIC_TMDB_API_KEY),
    tAiringToday(process.env.NEXT_PUBLIC_TMDB_API_KEY),
  ]);


  const ftdResults = trendDay.results.map(async(data) => {
    const {img, svg} = await getPlaiceholder(`https://image.tmdb.org/t/p/original/${data.poster_path}`)
    return {...data, img, svg}
  })

  
  const ftwResults = trendWeek.results.map(async(data) => {
    data.media = 'movie'
    const {img, svg} = await getPlaiceholder(`https://image.tmdb.org/t/p/original/${data.poster_path}`)
    return {...data, img, svg}
  })

  
  const mnpResults = moviesNowPlaying.results.map(async(data) => {
    data.media = 'movie'
    const {img, svg} = await getPlaiceholder(`https://image.tmdb.org/t/p/original/${data.poster_path}`)
    return {...data, img, svg}
  })

  
  const mtResults = moviesTopRated.results.map(async(data) => {
    data.media = 'movie'
    const {img, svg} = await getPlaiceholder(`https://image.tmdb.org/t/p/original/${data.poster_path}`)
    return {...data, img, svg}
  })
  
  
  
  const ttrResults = tvTopRated.results.map(async(data) => {
    data.media = 'tv'
    const {img, svg} = await getPlaiceholder(`https://image.tmdb.org/t/p/original/${data.poster_path}`)
    return {...data, img, svg}
  })
  
  
  const tatResults = tvAiringToday.results.map(async(data) => {
    data.media = 'tv'
    const {img, svg} = await getPlaiceholder(`https://image.tmdb.org/t/p/original/${data.poster_path}`)
    return {...data, img, svg}
  })
  
  // const ftw = await Promise.all(ftwResults)
  // const ftd = await Promise.all(ftdResults)
  // const mtr = await Promise.all(mtResults)
  // const mnpr = await Promise.all(mnpResults)
  // const tat = await Promise.all(tatResults)
  // const ttr = await Promise.all(ttrResults)
  
  const data = {
    trendDay,
    trendWeek,
    moviesNowPlaying,
    moviesTopRated,
    tvTopRated,
    tvAiringToday,
  };

  return {
    props: {
      data,
    },
  };
}

// trendDay: {...trendDay, results: ftd},
    // trendWeek: {...trendWeek, results: ftw},
    // moviesNowPlaying: {...moviesNowPlaying, results: mnpr},
    // moviesTopRated: {...moviesTopRated, results: mtr},
    // tvTopRated: {...tvTopRated, results: ttr},
    // tvAiringToday: {...tvAiringToday, results: tat},