import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { HomePage } from "@/components/home-page";
import { Navbar } from "@/components/navbar";
import Head from "next/head";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title> Flexmovies </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
      <Header />
      <HomePage data={data} />
      <Footer />
    </>
  );
}
