import { User } from "@/components/userpage";
import { useFavContext } from "@/context/FavouriteContext";
import { useWatchContext } from "@/context/WatchListContext";
import Head from "next/head";
import React from "react";

export default function UserPage() {
  const fav = useFavContext();

  const watch = useWatchContext();

  return (
    <>
      <Head>
        <title> Account || Flexmovies </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <User favorites={fav} watchlist={watch} />
    </>
  );
}
