import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { Navbar } from "@/components/navbar";
import { User } from "@/components/userpage";
import { useAuth } from "@/context/AuthUserContext";
import { useFavContext } from "@/context/FavouriteContext";
import { useWatchContext } from "@/context/WatchListContext";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

export default function UserPage() {
  const { user } = useAuth();
  const router = useRouter()

  if (!user) {
    router.push('/login')
  }

  const fav = useFavContext();

  const watch = useWatchContext();

  return (
    <>
      <Head>
        <title> Account || Flexmovies </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <User favorites={fav} watchlist={watch} />
    </>
  );
}
