import { User } from "@/components/userPage";
import Head from "next/head";
import React from "react";

export default function UserPage() {

  return (
    <>
      <Head>
        <title> Account || Flexmovies </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <User />
    </>
  );
}
