import Head from "next/head";
import styles from "@/styles/VerificationUI.module.scss";
import { handleVerifyEmail } from "@/lib/auth_handle_email_verification";
import { auth } from "@/firebase";
import { useEffect, useState } from "react";
import { FaSpinner } from "react-icons/fa6";
import { Router, useRouter } from "next/router";

const EmailVerificationUI = ({ actionCode, continueUrl }) => {
  const [ui, setUi] = useState(null);

  const router = useRouter()

  const handleClick = () => router.push('/')

  useEffect(() => {
    handleVerifyEmail(auth, actionCode, setUi);
  }, []);

  if (!ui) return <FaSpinner style={{fontSize: `4rem`}} />;

  if (ui && ui == "success") {
    return (
      <>
        <Head>
          <title>Email Verification </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className={styles.veri_page}>
          <section>
            <p className={styles.confirmation_text}>
              Your email has been successfully verified
            </p>
            <button className={styles.continue_btn}>
              continue to home page
            </button>
          </section>
        </main>
      </>
    );
  }

  if (ui && ui == "error") {
    return (
      <>
        <Head>
          <title>Email Verification </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className={styles.veri_page}>
          <section>
            <p className={styles.confirmation_text} onClick={handleClick}>
              Oops, there was an error, link has expired.
            </p>
            <p>Try verifying your email address again.</p>
            <button className={styles.continue_btn} onClick={handleClick}>
              continue to home page
            </button>
          </section>
        </main>
      </>
    );
  }
};
export default EmailVerificationUI;
