import Head from "next/head";

const ResetPasswordUI = () => {

    return (
      <>
        <Head>
          <title>Email Verified </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main>
          <section>
            <h2>Your Email has been successfully verified</h2>
          </section>
        </main>
      </>
    );
  };
  export default ResetPasswordUI
  