import React from "react";
import { Moviepage } from "@/components/moviePage";
import { fetchMovie, fetchMovieCast } from "@/utils/fetch";
import Head from "next/head";

const MoviePage = ({ movie, movieCast }) => (
  <>
    <Head>
      <title>{movie.title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <Moviepage item={movie} casts={movieCast} />
  </>
);

export default MoviePage;

export async function getServerSideProps(context) {
  const movieId = context.query.movie;
  const [movie, movieCast] = await Promise.all([
    fetchMovie(movieId, process.env.NEXT_PUBLIC_TMDB_API_KEY),
    fetchMovieCast(movieId, process.env.NEXT_PUBLIC_TMDB_API_KEY),
  ]);

  return {
    props: {
      movie,
      movieCast,
    },
  };
}
